development:
  encoding: utf8
  database: relational_database
  username: root
  password: 
  adapter: mysql2
  port: 3306
data_warehouse:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: data_warehouse
  username: longnguyen
  password:
  port: 5432