development:
  encoding: utf8
  database: relational_database
  username: root
  password: Ayanishitani1987*smt
  adapter: mysql2
  port: 3306
data_warehouse:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: data_warehouse
  username: dreaith
  password: Ayanishitani1987*smt
  port: 5432